---
deployment:
      tasks:
        - export DEPLOYPATH=/home1/spofnkte/public_html  # Add /<app_folder> if required
      
        - /bin cp * $DEPLOYPATH                           #copy all from root
        
        
